import type { Metadata } from "next";
import { Amaranth } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

import BackgroundTheme from "@/components/background-theme";

// Fonts
const amarnath = Amaranth({
  weight: ['400', '700'],
  // subsets: ['Regular','italic'],
  subsets: ['latin'],
  display: 'swap',
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${amarnath.className} antialiased scroll-smooth`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <BackgroundTheme>
            {children}
          </BackgroundTheme>
        </ThemeProvider>
      </body>
    </html>
  );
}
